//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPEIPlugin
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType=true)]
    [System.Xml.Serialization.XmlRoot(Namespace="", IsNullable=false)]
    public class splashwindow {
    
        private windowControls[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement("controls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public windowControls[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType=true)]
    public partial class windowControls {
    
        private windowControlsControl[] controlField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement("control", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public windowControlsControl[] control {
            get {
                return this.controlField;
            }
            set {
                this.controlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType=true)]
    public partial class windowControlsControl {
    
        private string descriptionField;
    
        private string typeField;
    
        private string idField;
    
        private string textsizeField;
    
        private string textcolorField;
    
        private string textureField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string textsize {
            get {
                return this.textsizeField;
            }
            set {
                this.textsizeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string textcolor {
            get {
                return this.textcolorField;
            }
            set {
                this.textcolorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string texture {
            get {
                return this.textureField;
            }
            set {
                this.textureField = value;
            }
        }
    }
}

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 